services:
    api:
      build: ./app

    nginx:
        image: nginx:1.27.4
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - api

    graphite:
        image: graphiteapp/graphite-statsd:1.1.10-5
        volumes:
            - ./statsd.config.json:/opt/statsd/config/udp.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:11.5.2
        ports:
            - "80:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.49.2
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s" --docker_only=true
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

    perf:
        build: ./perf
        links:
            - nginx
            - graphite
        depends_on:
            - api
            - nginx
            - graphite
        environment:
            - TARGET_HOST=nginx
            - STATSD_HOST=graphite
            - STATSD_PORT=8125

volumes:
    grafana_config:
        driver: local
